#:schema node_modules/wrangler/config-schema.json
name = "ai-learning"
compatibility_date = "2024-10-03"
compatibility_flags = ["nodejs_compat"]
main = "./dist/worker/index.js"
assets = { directory = "./dist/public", binding = "ASSETS" }


[vars]
TEST_VAR = "test"